In [19]:
data = [10, 20, 30, 40]
print("Head:", data[0])


Head: 10


In [20]:
data = [10, 20, 30, 40]
print("Tail:", data[-1])


Tail: 40


In [21]:
data = [10, 20, 5, 40]
print("Minimum:", min(data))


Minimum: 5


In [22]:
data = [10, 20, 5, 40]
print("Maximum:", max(data))


Maximum: 40


In [23]:
import numpy as np
data = np.array([[1, 2], [3, 4]])
print("Dimension:", data.ndim)


Dimension: 2


In [24]:
import numpy as np
array = np.array([20,30,50])
print("array:\n",array)
print("Head:",array[0])
print("Tail:",array[-1])
print("Minimum:",array.min())
print("Maximum:",array.max())
print("Dimension:",array.ndim,"D")

array:
 [20 30 50]
Head: 20
Tail: 50
Minimum: 20
Maximum: 50
Dimension: 1 D


In [14]:
import numpy as np
arr = np.array([10, 20, 30, 40])
print(arr.size)


4


In [2]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr.shape)


(2, 3)


In [3]:
print(arr.dtype)


int32


In [4]:
print(arr.sum())



21


In [5]:
print(arr.mean())


3.5


In [6]:
print(np.median(arr))


3.5


In [7]:
print(np.std(arr))


1.707825127659933


In [8]:
print(np.var(arr))


2.9166666666666665


In [9]:
print(np.sort(arr))


[[1 2 3]
 [4 5 6]]


In [10]:
arr2 = np.array([1, 2, 2, 3, 4, 4])
print(np.unique(arr2))


[1 2 3 4]


In [11]:
print(arr.argmin())  
print(arr.argmax())  


0
5


In [12]:
print(arr[::-1])


[[4 5 6]
 [1 2 3]]


In [13]:
import pandas as pd
data = {
    "A": [10, 20, 30],
    "B": [40, 50, 60]
}
df = pd.DataFrame(data)
print(df.columns)     
print(df["A"])         
print(df.mean())      


Index(['A', 'B'], dtype='object')
0    10
1    20
2    30
Name: A, dtype: int64
A    20.0
B    50.0
dtype: float64
